### ISSUE TITLE
Ist feEditable sinnvoll?

### ISSUE THREAD

**Issue by fiedsch** [christianbarkowsky/contao-privacyconsent-bundle#3]
Hallo Christian,

erst Mal Danke für Deinen Einsatz und das Bundle!

Duch `'feEditable'=>true` in `$GLOBALS['TL_DCA']['tl_member']['fields']['privacyConsent']['eval']` könnte der angemeldete User im FE seine Zustimmung wieder entziehen (falls es eine Seite mit einem `ModulePersonalData` gibt, bei dem `privacyConsent` ausgewählt ist).

Als Website-Betreiber würde ich mich dann fragen, was passieren soll, wenn der User seine Zustimmung entzieht. Konto löschen, Login verhindern, ...?

Lange Rede, kurzer Sinn: aus meiner Sicht ergibt `'feEditable'=>true` keinen/wenig Sinn.

**Comment by christianbarkowsky** [comment]
Das habe ich wohl auf die Schnelle übersehen. Danke @fiedsch

**Comment by felixpfeiffer** [comment]
Das Problem ist aber, dass ohne feEditable das Feld dann im Registrierungs-Modul nicht als Feld zur Verfügung steht.

Ich denke, die Verantwortung, in welchem Modul das Feld angezeigt wird, muss in den Händen des Administrators liegen.

**Comment by christianbarkowsky** [comment]
Geprüft. feEditable bleibt true.
